package org.cc.jpa.controller;

import org.cc.jpa.entity.UserLaud;
import org.cc.jpa.repository.UserLaudRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class UserLaudController {

	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private UserLaudRepository userRepository;

	@GetMapping(path = "/list") // Map ONLY GET Requests
	public Iterable<UserLaud> addNewUser() {
		return userRepository.findAll();
	}
}
