spring:
   application:
      name: shardingtest

server:
   port: 7112

spring: 
   shardingsphere:
      datasource:
         names: ds0,ds1
         ds0: 
            type: com.alibaba.druid.pool.DruidDataSource
            driver-class-name: com.mysql.cj.jdbc.Driver
            url: 
            username: 
            password: 
         ds1: 
            type: com.alibaba.druid.pool.DruidDataSource
            driver-class-name: com.mysql.cj.jdbc.Driver
            url: 
            username: 
            password: 
         sharding:
            tables:
               t_order:
                  actual-data-nodes: ds$->{0..1}.t_order$->{0..1}
                  table-strategy:
                     inline:
                        sharding-column: order_id
                        algorithm-expression: t_order$->{order_id % 2}
                     key-generator:
                        column: order_id
                        type: SNOWFLAKE