spring:
   application:
      name: TestServer

server:
   port: 7111

eureka:
   password: 
   client:
      serviceUrl:
         defaultZone: http://eureka.springcloud.cn/eureka/   
      